SELECT * FROM (WITH
CAPA_DUIMP AS (
    SELECT X.NUMERODUIMP, X.COTACAODOLAR, X.FRETE FRETE_DUIMP, X.SEGURO SEGURO_DUIMP,
           X.TAXASISCOMEX TAXASISCOMEX_DUIMP, X.SEQPEDIDOIMPORT SEQPED_VINCULADO
      FROM NAGT_DUIMP_CAPA X
     WHERE X.NUMERODUIMP = :LT1
),
PEDIDO_C5 AS (
    SELECT P.SEQPEDIDOIMPORT, P.TXCAMBIO CAMBIO_C5
      FROM MAD_PIPEDIDOIMPORT P
     WHERE P.SEQPEDIDOIMPORT = :NR1
),
DESPESA_C5 AS (
    SELECT MAX(CASE WHEN T.DESCTIPOADIANT = 'FRETE INTERNACIONAL' THEN D.VLRDESPESA END) FRETE_C5,
           MAX(CASE WHEN T.DESCTIPOADIANT = 'SEGURO'               THEN D.VLRDESPESA END) SEGURO_C5,
           MAX(CASE WHEN T.DESCTIPOADIANT = 'TAXA SISCOMEX'        THEN D.VLRDESPESA END) TAXASISCOMEX_C5
      FROM MAD_PIPEDDESPESA D JOIN MAD_PITIPOADIANTAMENTO T ON T.SEQTIPOADIANT = D.SEQTIPOADIANT
     WHERE D.SEQPEDIDOIMPORT = :NR1
),
CAPA_UNICA AS (

    SELECT CAP.NUMERODUIMP,
           CAP.COTACAODOLAR, PED.CAMBIO_C5, CAP.COTACAODOLAR - PED.CAMBIO_C5 DIF_CAMBIO,
           CAP.FRETE_DUIMP, DESP.FRETE_C5, CAP.FRETE_DUIMP - DESP.FRETE_C5 DIF_FRETE,
           CAP.SEGURO_DUIMP, DESP.SEGURO_C5, CAP.SEGURO_DUIMP - DESP.SEGURO_C5 DIF_SEGURO,
           CAP.TAXASISCOMEX_DUIMP, DESP.TAXASISCOMEX_C5, CAP.TAXASISCOMEX_DUIMP - DESP.TAXASISCOMEX_C5 DIF_TAXASISCOMEX,
           CASE WHEN CAP.SEQPED_VINCULADO IS NULL THEN 'DUIMP_NAO_VINCULADA_AO_PEDIDO'
                WHEN TO_CHAR(CAP.SEQPED_VINCULADO) != :NR1 THEN 'VINCULADA_A_OUTRO_PEDIDO'
                WHEN ABS(NVL(CAP.COTACAODOLAR,0) - NVL(PED.CAMBIO_C5,0)) > 0.0001 THEN 'DIVERGENTE'
                ELSE 'OK' END STATUS_CAMBIO,
           CASE WHEN CAP.SEQPED_VINCULADO IS NULL THEN 'DUIMP_NAO_VINCULADA_AO_PEDIDO'
                WHEN TO_CHAR(CAP.SEQPED_VINCULADO) != :NR1 THEN 'VINCULADA_A_OUTRO_PEDIDO'
                WHEN ABS(NVL(CAP.FRETE_DUIMP,0) - NVL(DESP.FRETE_C5,0)) > 0.01 THEN 'DIVERGENTE'
                ELSE 'OK' END STATUS_FRETE,
           CASE WHEN CAP.SEQPED_VINCULADO IS NULL THEN 'DUIMP_NAO_VINCULADA_AO_PEDIDO'
                WHEN TO_CHAR(CAP.SEQPED_VINCULADO) != :NR1 THEN 'VINCULADA_A_OUTRO_PEDIDO'
                WHEN ABS(NVL(CAP.SEGURO_DUIMP,0) - NVL(DESP.SEGURO_C5,0)) > 0.01 THEN 'DIVERGENTE'
                ELSE 'OK' END STATUS_SEGURO,
           CASE WHEN CAP.SEQPED_VINCULADO IS NULL THEN 'DUIMP_NAO_VINCULADA_AO_PEDIDO'
                WHEN TO_CHAR(CAP.SEQPED_VINCULADO) != :NR1 THEN 'VINCULADA_A_OUTRO_PEDIDO'
                WHEN ABS(NVL(CAP.TAXASISCOMEX_DUIMP,0) - NVL(DESP.TAXASISCOMEX_C5,0)) > 0.01 THEN 'DIVERGENTE'
                ELSE 'OK' END STATUS_TAXASISCOMEX
      FROM CAPA_DUIMP CAP CROSS JOIN PEDIDO_C5 PED CROSS JOIN DESPESA_C5 DESP
),
DUIMP_AGG AS (
    SELECT X.CODIGO,
           MAX(X.DESCRICAO)         DESCRICAO,
           SUM(X.QUANTIDADE)        QUANTIDADE,
           SUM(X.PESO_LIQUIDO)      PESO_LIQUIDO,
           SUM(X.VALORII)           VALORII,       MAX(X.ALIQUOTAII)     ALIQUOTAII,
           SUM(X.VALORIPI)          VALORIPI,      MAX(X.ALIQUOTAIPI)    ALIQUOTAIPI,
           SUM(X.VALORPIS)          VALORPIS,      MAX(X.ALIQUOTAPIS)    ALIQUOTAPIS,
           SUM(X.VALORCOFINS)       VALORCOFINS,   MAX(X.ALIQUOTACOFINS) ALIQUOTACOFINS
      FROM NAGT_DUIMP_ITENS X
     WHERE X.NUMERODUIMP = :LT1
     GROUP BY X.CODIGO
),
ERP_AGG AS (
    SELECT A.SEQPRODUTO     CODIGO,
           B.DESCCOMPLETA,
           A.QTDSOLICITADA  QTD_C5,
           A.QTDEMBALAGEM   QTDEMBALAGEM_C5,
           D.PESOLIQUIDO    PESO_CAIXA_C5,
           ROUND(D.PESOLIQUIDO * A.QTDSOLICITADA / NULLIF(A.QTDEMBALAGEM,0), 3) PESO_ESPERADO_C5,
           A.VLRIMPIMPORT   VLRIMPIMPORT_C5,  A.PERIMPOSTIMPORT PERIMPOSTIMPORT_C5,
           A.VLRIPI         VLRIPI_C5,        A.PERALIQIPI      PERALIQIPI_C5,
           A.VLRPIS         VLRPIS_C5,        T.PERPISDIF    + NVL(T.PERMAJORACAOPISIMPORT,0)    PERPIS_C5,
           A.VLRCOFINS      VLRCOFINS_C5,     T.PERCOFINSDIF + NVL(T.PERMAJORACAOCOFINSIMPORT,0)  PERCOFINS_C5, EMBALAGEM||'-'||D.QTDEMBALAGEM EMB
      FROM MAD_PIPEDIMPORTPROD A INNER JOIN MAP_PRODUTO B      ON A.SEQPRODUTO = B.SEQPRODUTO
                                  INNER JOIN MAP_FAMEMBALAGEM D ON D.SEQFAMILIA = B.SEQFAMILIA AND D.QTDEMBALAGEM = A.QTDEMBALAGEM
                                  INNER JOIN MAP_FAMDIVISAO F   ON F.SEQFAMILIA = B.SEQFAMILIA
                                  INNER JOIN MAP_TRIBUTACAOUF T ON T.NROTRIBUTACAO = F.NROTRIBUTACAO AND T.NROREGTRIBUTACAO = 8
                                                               AND T.UFEMPRESA = 'SP' AND T.UFCLIENTEFORNEC = 'EX' AND T.TIPTRIBUTACAO = 'EI'
     WHERE A.SEQPEDIDOIMPORT = :NR1
),
RELATORIO AS (
    SELECT
           NVL(TO_CHAR(E.CODIGO), D.CODIGO)    PLU,
           NVL(E.DESCCOMPLETA, D.DESCRICAO)    DESCRICAO,
           D.QUANTIDADE          QTD_DUIMP,
           E.QTD_C5,
           D.QUANTIDADE - E.QTD_C5              DIF_QTD,
           E.PESO_CAIXA_C5,
           ROUND(D.PESO_LIQUIDO * E.QTDEMBALAGEM_C5 / NULLIF(E.QTD_C5,0), 3) PESO_DUIMP_CAIXA,
           ROUND(D.PESO_LIQUIDO * E.QTDEMBALAGEM_C5 / NULLIF(E.QTD_C5,0), 3) - E.PESO_CAIXA_C5 DIF_PESO_CAIXA,
           D.PESO_LIQUIDO        PESO_DUIMP,
           E.PESO_ESPERADO_C5,
           D.PESO_LIQUIDO - E.PESO_ESPERADO_C5  DIF_PESO,
           D.VALORII,     E.VLRIMPIMPORT_C5,  D.VALORII     - E.VLRIMPIMPORT_C5  DIF_II,
           D.ALIQUOTAII,  E.PERIMPOSTIMPORT_C5, D.ALIQUOTAII - E.PERIMPOSTIMPORT_C5 DIF_PERII,
           D.VALORIPI,    E.VLRIPI_C5,        D.VALORIPI    - E.VLRIPI_C5       DIF_IPI,
           D.ALIQUOTAIPI, E.PERALIQIPI_C5,    D.ALIQUOTAIPI - E.PERALIQIPI_C5   DIF_PERIPI,
           D.VALORPIS,    E.VLRPIS_C5,        D.VALORPIS    - E.VLRPIS_C5       DIF_PIS,
           D.ALIQUOTAPIS, E.PERPIS_C5,        D.ALIQUOTAPIS - E.PERPIS_C5       DIF_PERPIS,
           D.VALORCOFINS, E.VLRCOFINS_C5,     D.VALORCOFINS - E.VLRCOFINS_C5    DIF_COFINS,
           D.ALIQUOTACOFINS, E.PERCOFINS_C5,  D.ALIQUOTACOFINS - E.PERCOFINS_C5 DIF_PERCOFINS,
           CASE WHEN D.CODIGO IS NULL THEN 'NAO_ENCONTRADO_NA_DUIMP'
                WHEN E.CODIGO IS NULL THEN 'NAO_ENCONTRADO_NO_PEDIDO'
                WHEN ABS(NVL(D.QUANTIDADE,0) - NVL(E.QTD_C5,0)) > 0.001 THEN 'DIVERGENTE'
                ELSE 'OK' END STATUS_QTD,
           CASE WHEN ABS(ROUND(D.PESO_LIQUIDO * E.QTDEMBALAGEM_C5 / NULLIF(E.QTD_C5,0), 3) - NVL(E.PESO_CAIXA_C5,0)) > 0.1
                THEN 'DIVERGENTE' ELSE 'OK' END STATUS_PESO,
           CASE WHEN D.CODIGO IS NULL THEN 'NAO_ENCONTRADO_NA_DUIMP'
                WHEN E.CODIGO IS NULL THEN 'NAO_ENCONTRADO_NO_PEDIDO'
                WHEN ABS(NVL(D.VALORII,0) - NVL(E.VLRIMPIMPORT_C5,0)) > 0.01 THEN 'DIVERGENTE'
                ELSE 'OK' END STATUS_II_VALOR,
           CASE WHEN D.CODIGO IS NULL THEN 'NAO_ENCONTRADO_NA_DUIMP'
                WHEN E.CODIGO IS NULL THEN 'NAO_ENCONTRADO_NO_PEDIDO'
                WHEN ABS(NVL(D.ALIQUOTAII,0) - NVL(E.PERIMPOSTIMPORT_C5,0)) > 0.01 THEN 'DIVERGENTE'
                ELSE 'OK' END STATUS_II_ALIQ,
           CASE WHEN D.CODIGO IS NULL THEN 'NAO_ENCONTRADO_NA_DUIMP'
                WHEN E.CODIGO IS NULL THEN 'NAO_ENCONTRADO_NO_PEDIDO'
                WHEN ABS(NVL(D.VALORIPI,0) - NVL(E.VLRIPI_C5,0)) > 0.01 THEN 'DIVERGENTE'
                ELSE 'OK' END STATUS_IPI_VALOR,
           CASE WHEN D.CODIGO IS NULL THEN 'NAO_ENCONTRADO_NA_DUIMP'
                WHEN E.CODIGO IS NULL THEN 'NAO_ENCONTRADO_NO_PEDIDO'
                WHEN ABS(NVL(D.ALIQUOTAIPI,0) - NVL(E.PERALIQIPI_C5,0)) > 0.01 THEN 'DIVERGENTE'
                ELSE 'OK' END STATUS_IPI_ALIQ,
           CASE WHEN D.CODIGO IS NULL THEN 'NAO_ENCONTRADO_NA_DUIMP'
                WHEN E.CODIGO IS NULL THEN 'NAO_ENCONTRADO_NO_PEDIDO'
                WHEN ABS(NVL(D.VALORPIS,0) - NVL(E.VLRPIS_C5,0)) > 0.01 THEN 'DIVERGENTE'
                ELSE 'OK' END STATUS_PIS_VALOR,
           CASE WHEN D.CODIGO IS NULL THEN 'NAO_ENCONTRADO_NA_DUIMP'
                WHEN E.CODIGO IS NULL THEN 'NAO_ENCONTRADO_NO_PEDIDO'
                WHEN ABS(NVL(D.ALIQUOTAPIS,0) - NVL(E.PERPIS_C5,0)) > 0.01 THEN 'DIVERGENTE'
                ELSE 'OK' END STATUS_PIS_ALIQ,
           CASE WHEN D.CODIGO IS NULL THEN 'NAO_ENCONTRADO_NA_DUIMP'
                WHEN E.CODIGO IS NULL THEN 'NAO_ENCONTRADO_NO_PEDIDO'
                WHEN ABS(NVL(D.VALORCOFINS,0) - NVL(E.VLRCOFINS_C5,0)) > 0.01 THEN 'DIVERGENTE'
                ELSE 'OK' END STATUS_COFINS_VALOR, 
           CASE WHEN D.CODIGO IS NULL THEN 'NAO_ENCONTRADO_NA_DUIMP'
                WHEN E.CODIGO IS NULL THEN 'NAO_ENCONTRADO_NO_PEDIDO'
                WHEN ABS(NVL(D.ALIQUOTACOFINS,0) - NVL(E.PERCOFINS_C5,0)) > 0.01 THEN 'DIVERGENTE'
                ELSE 'OK' END STATUS_COFINS_ALIQ, EMB
      FROM DUIMP_AGG D FULL OUTER JOIN ERP_AGG E ON TO_CHAR(E.CODIGO) = D.CODIGO
)
SELECT X.NUMERODUIMP, ORD, GRUPO, TRIBUTO, PLU, DESCRICAO, VALOR_DUIMP, VALOR_C5, DIFERENCA, STATUS, P.SEQPEDIDOIMPORT PED
  FROM (
    SELECT 1 ORD, 'Despesas / Câmbio' GRUPO, 'Câmbio' TRIBUTO, NULL PLU, NULL DESCRICAO,
       CASE WHEN COTACAODOLAR IS NULL THEN NULL ELSE TO_CHAR(COTACAODOLAR, 'FM999G990D0000', 'NLS_NUMERIC_CHARACTERS = '',.''') END VALOR_DUIMP,
       CASE WHEN CAMBIO_C5    IS NULL THEN NULL ELSE TO_CHAR(CAMBIO_C5,    'FM999G990D0000', 'NLS_NUMERIC_CHARACTERS = '',.''') END VALOR_C5,
       CASE WHEN DIF_CAMBIO   IS NULL THEN NULL ELSE TO_CHAR(DIF_CAMBIO,   'FM999G990D0000', 'NLS_NUMERIC_CHARACTERS = '',.''') END DIFERENCA,
       STATUS_CAMBIO STATUS, 0 ORDEM_GRUPO, 1 ORDEM_TRIB
       FROM CAPA_UNICA
    UNION ALL
    SELECT 1, 'Despesas / Câmbio' GRUPO, 'Frete' TRIBUTO, NULL, NULL,
           CASE WHEN FRETE_DUIMP IS NULL THEN NULL ELSE 'R$ ' || TO_CHAR(FRETE_DUIMP, 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') END,
           CASE WHEN FRETE_C5    IS NULL THEN NULL ELSE 'R$ ' || TO_CHAR(FRETE_C5,    'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') END,
           CASE WHEN DIF_FRETE   IS NULL THEN NULL ELSE 'R$ ' || TO_CHAR(DIF_FRETE,   'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') END,
           STATUS_FRETE, 0, 2
      FROM CAPA_UNICA
    UNION ALL
    SELECT 1, 'Despesas / Câmbio' GRUPO, 'Seguro' TRIBUTO, NULL, NULL,
           CASE WHEN SEGURO_DUIMP IS NULL THEN NULL ELSE 'R$ ' || TO_CHAR(SEGURO_DUIMP, 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') END,
           CASE WHEN SEGURO_C5    IS NULL THEN NULL ELSE 'R$ ' || TO_CHAR(SEGURO_C5,    'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') END,
           CASE WHEN DIF_SEGURO   IS NULL THEN NULL ELSE 'R$ ' || TO_CHAR(DIF_SEGURO,   'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') END,
           STATUS_SEGURO, 0, 3
      FROM CAPA_UNICA
    UNION ALL
    SELECT 1, 'Despesas / Câmbio' GRUPO, 'Taxa Siscomex' TRIBUTO, NULL, NULL,
           CASE WHEN TAXASISCOMEX_DUIMP IS NULL THEN NULL ELSE 'R$ ' || TO_CHAR(TAXASISCOMEX_DUIMP, 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') END,
           CASE WHEN TAXASISCOMEX_C5    IS NULL THEN NULL ELSE 'R$ ' || TO_CHAR(TAXASISCOMEX_C5,    'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') END,
           CASE WHEN DIF_TAXASISCOMEX   IS NULL THEN NULL ELSE 'R$ ' || TO_CHAR(DIF_TAXASISCOMEX,   'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') END,
           STATUS_TAXASISCOMEX, 0, 4
      FROM CAPA_UNICA
    UNION ALL
    SELECT 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 5
      FROM DUAL
    UNION ALL
    SELECT 1, 'Despesas / Câmbio', 'SUBTOTAL' TRIBUTO, NULL, NULL,
           'R$ ' || TO_CHAR(NVL(FRETE_DUIMP,0)+NVL(SEGURO_DUIMP,0)+NVL(TAXASISCOMEX_DUIMP,0), 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.'''),
           'R$ ' || TO_CHAR(NVL(FRETE_C5,0)+NVL(SEGURO_C5,0)+NVL(TAXASISCOMEX_C5,0), 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.'''),
           'R$ ' || TO_CHAR((NVL(FRETE_DUIMP,0)+NVL(SEGURO_DUIMP,0)+NVL(TAXASISCOMEX_DUIMP,0)) - (NVL(FRETE_C5,0)+NVL(SEGURO_C5,0)+NVL(TAXASISCOMEX_C5,0)), 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.'''),
           NULL, 0, 6
      FROM CAPA_UNICA
    UNION ALL
    SELECT 2.1, 'Quantidade' GRUPO, 'Quantidade' TRIBUTO, PLU, DESCRICAO,
           TO_CHAR(QTD_DUIMP) VALOR_DUIMP, TO_CHAR(QTD_C5) VALOR_C5, TO_CHAR(DIF_QTD) DIFERENCA,
           STATUS_QTD, 1, 1
      FROM RELATORIO
    UNION ALL
    SELECT 2, 'Peso' GRUPO, 'Peso ('||EMB||')' TRIBUTO, PLU, DESCRICAO,
           TO_CHAR(PESO_DUIMP_CAIXA, 'FM999G990D000', 'NLS_NUMERIC_CHARACTERS = '',.''') VALOR_DUIMP,
           TO_CHAR(PESO_CAIXA_C5,    'FM999G990D000', 'NLS_NUMERIC_CHARACTERS = '',.''') VALOR_C5,
           TO_CHAR(DIF_PESO_CAIXA,   'FM999G990D000', 'NLS_NUMERIC_CHARACTERS = '',.''') DIFERENCA,
           STATUS_PESO, 2, 1
      FROM RELATORIO
    UNION ALL
    SELECT 7, 'Impostos - Valores' GRUPO, 'II - Valor' TRIBUTO, PLU, DESCRICAO,
           CASE WHEN VALORII         IS NULL THEN NULL ELSE 'R$ ' || TO_CHAR(VALORII,         'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') END,
           CASE WHEN VLRIMPIMPORT_C5 IS NULL THEN NULL ELSE 'R$ ' || TO_CHAR(VLRIMPIMPORT_C5, 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') END,
           CASE WHEN DIF_II          IS NULL THEN NULL ELSE 'R$ ' || TO_CHAR(DIF_II,          'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') END,
           STATUS_II_VALOR, 3, 1
      FROM RELATORIO
    UNION ALL
    SELECT 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 5
      FROM DUAL
    UNION ALL
    SELECT 7, 'Impostos - Valores', 'SUBTOTAL II' TRIBUTO, NULL, NULL,
           'R$ ' || TO_CHAR(SUM(NVL(VALORII,0)),         'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.'''),
           'R$ ' || TO_CHAR(SUM(NVL(VLRIMPIMPORT_C5,0)), 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.'''),
           'R$ ' || TO_CHAR(SUM(NVL(VALORII,0)) - SUM(NVL(VLRIMPIMPORT_C5,0)), 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.'''),
           NULL, 3, 6
      FROM RELATORIO
    UNION ALL
    SELECT 8, 'Impostos - Valores' GRUPO, 'IPI - Valor' TRIBUTO, PLU, DESCRICAO,
           CASE WHEN VALORIPI  IS NULL THEN NULL ELSE 'R$ ' || TO_CHAR(VALORIPI,  'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') END,
           CASE WHEN VLRIPI_C5 IS NULL THEN NULL ELSE 'R$ ' || TO_CHAR(VLRIPI_C5, 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') END,
           CASE WHEN DIF_IPI   IS NULL THEN NULL ELSE 'R$ ' || TO_CHAR(DIF_IPI,   'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') END,
           STATUS_IPI_VALOR, 3, 2
      FROM RELATORIO
    UNION ALL
    SELECT 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 5
      FROM DUAL
    UNION ALL
    SELECT 8, 'Impostos - Valores', 'SUBTOTAL IPI' TRIBUTO, NULL, NULL,
           'R$ ' || TO_CHAR(SUM(NVL(VALORIPI,0)),  'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.'''),
           'R$ ' || TO_CHAR(SUM(NVL(VLRIPI_C5,0)), 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.'''),
           'R$ ' || TO_CHAR(SUM(NVL(VALORIPI,0)) - SUM(NVL(VLRIPI_C5,0)), 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.'''),
           NULL, 3, 6
      FROM RELATORIO
    UNION ALL
    SELECT 9, 'Impostos - Valores' GRUPO, 'PIS - Valor' TRIBUTO, PLU, DESCRICAO,
           CASE WHEN VALORPIS  IS NULL THEN NULL ELSE 'R$ ' || TO_CHAR(VALORPIS,  'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') END,
           CASE WHEN VLRPIS_C5 IS NULL THEN NULL ELSE 'R$ ' || TO_CHAR(VLRPIS_C5, 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') END,
           CASE WHEN DIF_PIS   IS NULL THEN NULL ELSE 'R$ ' || TO_CHAR(DIF_PIS,   'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') END,
           STATUS_PIS_VALOR, 3, 3
      FROM RELATORIO
    UNION ALL
    SELECT 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 5
      FROM DUAL
    UNION ALL
    SELECT 9, 'Impostos - Valores', 'SUBTOTAL PIS' TRIBUTO, NULL, NULL,
           'R$ ' || TO_CHAR(SUM(NVL(VALORPIS,0)),  'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.'''),
           'R$ ' || TO_CHAR(SUM(NVL(VLRPIS_C5,0)), 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.'''),
           'R$ ' || TO_CHAR(SUM(NVL(VALORPIS,0)) - SUM(NVL(VLRPIS_C5,0)), 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.'''),
           NULL, 3, 6
      FROM RELATORIO
    UNION ALL
    SELECT 10, 'Impostos - Valores' GRUPO, 'COFINS - Valor' TRIBUTO, PLU, DESCRICAO,
           CASE WHEN VALORCOFINS  IS NULL THEN NULL ELSE 'R$ ' || TO_CHAR(VALORCOFINS,  'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') END,
           CASE WHEN VLRCOFINS_C5 IS NULL THEN NULL ELSE 'R$ ' || TO_CHAR(VLRCOFINS_C5, 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') END,
           CASE WHEN DIF_COFINS   IS NULL THEN NULL ELSE 'R$ ' || TO_CHAR(DIF_COFINS,   'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') END,
           STATUS_COFINS_VALOR, 3, 4
      FROM RELATORIO
    UNION ALL
    SELECT 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 5
      FROM DUAL
    UNION ALL
    SELECT 10, 'Impostos - Valores', 'SUBTOTAL COFINS' TRIBUTO, NULL, NULL,
           'R$ ' || TO_CHAR(SUM(NVL(VALORCOFINS,0)),  'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.'''),
           'R$ ' || TO_CHAR(SUM(NVL(VLRCOFINS_C5,0)), 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.'''),
           'R$ ' || TO_CHAR(SUM(NVL(VALORCOFINS,0)) - SUM(NVL(VLRCOFINS_C5,0)), 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.'''),
           NULL, 3, 6
      FROM RELATORIO
    UNION ALL
    SELECT 3, 'Impostos - Alíquotas' GRUPO, 'II - Aliq' TRIBUTO, PLU, DESCRICAO,
           CASE WHEN ALIQUOTAII        IS NULL THEN NULL ELSE TO_CHAR(ALIQUOTAII,        'FM999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') || '%' END,
           CASE WHEN PERIMPOSTIMPORT_C5 IS NULL THEN NULL ELSE TO_CHAR(PERIMPOSTIMPORT_C5, 'FM999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') || '%' END,
           CASE WHEN DIF_PERII         IS NULL THEN NULL ELSE TO_CHAR(DIF_PERII,         'FM999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') || '%' END,
           STATUS_II_ALIQ, 4, 1
      FROM RELATORIO
    UNION ALL
    SELECT 4, 'Impostos - Alíquotas' GRUPO, 'IPI - Aliq' TRIBUTO, PLU, DESCRICAO,
           CASE WHEN ALIQUOTAIPI   IS NULL THEN NULL ELSE TO_CHAR(ALIQUOTAIPI,   'FM999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') || '%' END,
           CASE WHEN PERALIQIPI_C5 IS NULL THEN NULL ELSE TO_CHAR(PERALIQIPI_C5, 'FM999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') || '%' END,
           CASE WHEN DIF_PERIPI    IS NULL THEN NULL ELSE TO_CHAR(DIF_PERIPI,    'FM999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') || '%' END,
           STATUS_IPI_ALIQ, 4, 2
      FROM RELATORIO
    UNION ALL
    SELECT 5, 'Impostos - Alíquotas' GRUPO, 'PIS - Aliq' TRIBUTO, PLU, DESCRICAO,
           CASE WHEN ALIQUOTAPIS IS NULL THEN NULL ELSE TO_CHAR(ALIQUOTAPIS, 'FM999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') || '%' END,
           CASE WHEN PERPIS_C5   IS NULL THEN NULL ELSE TO_CHAR(PERPIS_C5,   'FM999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') || '%' END,
           CASE WHEN DIF_PERPIS  IS NULL THEN NULL ELSE TO_CHAR(DIF_PERPIS,  'FM999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') || '%' END,
           STATUS_PIS_ALIQ, 4, 3
      FROM RELATORIO
    UNION ALL
    SELECT 6, 'Impostos - Alíquotas' GRUPO, 'COFINS - Aliq' TRIBUTO, PLU, DESCRICAO,
           CASE WHEN ALIQUOTACOFINS IS NULL THEN NULL ELSE TO_CHAR(ALIQUOTACOFINS, 'FM999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') || '%' END,
           CASE WHEN PERCOFINS_C5   IS NULL THEN NULL ELSE TO_CHAR(PERCOFINS_C5,   'FM999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') || '%' END,
           CASE WHEN DIF_PERCOFINS  IS NULL THEN NULL ELSE TO_CHAR(DIF_PERCOFINS,  'FM999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') || '%' END,
           STATUS_COFINS_ALIQ, 4, 4
      FROM RELATORIO

  ) INNER JOIN CAPA_DUIMP X ON 1=1
    INNER JOIN PEDIDO_C5 P  ON 2=2
 ORDER BY 1, 2, ORDEM_GRUPO, PLU, ORDEM_TRIB);
 
 
