SELECT * FROM NAGT_DUIMP_CAPA;
SELECT * FROM NAGT_DUIMP_ITENS;

CREATE TABLE NAGT_DUIMP_CAPA (
  NUMERODUIMP           VARCHAR2(20)  NOT NULL,
  VERSAODUIMP           NUMBER,
  DATAXML               DATE,
  DATADUIMP             DATE,
  DATADOLAR             DATE,
  DATADESEMBARACO       DATE,
  UFDESEMBARACO         VARCHAR2(2),
  LOCALDESEMBARACO      VARCHAR2(100),
  COTACAODOLAR          NUMBER,
  TAXASISCOMEX          NUMBER,
  DESPESASADUANEIRAS    NUMBER,
  FRETE                 NUMBER,
  SEGURO                NUMBER,
  IPI                   NUMBER,
  PIS                   NUMBER,
  COFINS                NUMBER,
  II                    NUMBER,
  ICMS                  NUMBER,
  TOTALMATERIAISDOLAR   NUMBER,
  MOEDAMLE              VARCHAR2(5),
  VMLE                  NUMBER,
  VMLD                  NUMBER,
  INFOCOMPLEMENTARES    VARCHAR2(500),
  CNPJIMP               VARCHAR2(14),
  TIPOEMB               VARCHAR2(50),
  VLQTDEEMB             NUMBER,
  DTAIMPORTACAO         DATE          DEFAULT SYSDATE,
  NMARQUIVO             VARCHAR2(200),
  CONSTRAINT PK_NAGT_DUIMP_CAPA PRIMARY KEY (NUMERODUIMP)
);

CREATE TABLE NAGT_DUIMP_ITENS (
  NUMERODUIMP            VARCHAR2(20)   NOT NULL,
  IT                     NUMBER         NOT NULL,
  NUMEROADICAO           VARCHAR2(3),
  NUMEROITEM             VARCHAR2(4),
  CODIGO                 NUMBER,
  DESCRICAO              VARCHAR2(500),
  DESCRICAOCOMPLEMENTAR  VARCHAR2(2000),
  NCM                    VARCHAR2(10),
  UNIDADE                VARCHAR2(5),
  QUANTIDADE             NUMBER,
  VALORUNITARIODOLAR     NUMBER,
  PESO_LIQUIDO           NUMBER,
  PESO_BRUTO             NUMBER,
  ALIQUOTAPIS            NUMBER,
  ALIQUOTAPISREDUZIDA    NUMBER,
  BASECALCULOII          NUMBER,
  BASECALCULOIPI         NUMBER,
  BASECALCULOPISCOFINS   NUMBER,
  BASECALCULOICMS        NUMBER,
  VALORPIS               NUMBER,
  ALIQUOTACOFINS         NUMBER,
  ALIQUOTACOFINSREDUZIDA NUMBER,
  VALORCOFINS            NUMBER,
  ALIQUOTAIPI            NUMBER,
  VALORIPI               NUMBER,
  ALIQUOTAII             NUMBER,
  VALORII                NUMBER,
  EXPORTADOR             VARCHAR2(100),
  PAISORIGEM             VARCHAR2(50),
  FABRICANTE             VARCHAR2(100),
  CST                    VARCHAR2(3),
  CCLASSIF               VARCHAR2(10),
  VALORALIQIBS           NUMBER,
  VALORALIQICBS          NUMBER,
  VALORIBSUF             NUMBER,
  VALORIBSMUN            NUMBER,
  VALORCBS               NUMBER,
  CONSTRAINT PK_NAGT_DUIMP_ITENS PRIMARY KEY (NUMERODUIMP, IT),
  CONSTRAINT FK_NAGT_DUIMP_ITENS FOREIGN KEY (NUMERODUIMP)
    REFERENCES NAGT_DUIMP_CAPA (NUMERODUIMP)
);

ALTER TABLE NAGT_DUIMP_CAPA ADD XML_ORIGINAL CLOB;
ALTER TABLE NAGT_DUIMP_CAPA ADD IND_PROCESSADA NUMBER(10);
ALTER TABLE NAGT_DUIMP_CAPA ADD DTAPROCESSADA DATE;
ALTER TABLE NAGT_DUIMP_CAPA ADD SEQPEDIDOIMPORT NUMBER(10);
